# Generated by Django 4.0.5 on 2022-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('faction', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('muzzle_velocity', models.IntegerField()),
                ('refire_ms', models.IntegerField()),
                ('max_damage', models.IntegerField()),
                ('min_damage', models.IntegerField()),
                ('damage_max_range', models.IntegerField()),
                ('damage_min_range', models.IntegerField()),
            ],
        ),
    ]
